Fix .qubesbuilder: no need for ".in"
Building was failing with:

   error: line 2: Illegal char '@' (0x40) in: Version:    @VERSION@

This turns out be unecessary as QubesBuilderV2 already accounts for the
possibility of a `.in` naming.